import React from 'react';
import HeaderGreen from '../components/HeaderGreen';

export default function ThemesPage() {
  const brandingBoards = [
    { title: "CoffeeHaus Branding", image: "/images/board-1.png" },
    { title: "ZenTech Logo Kit", image: "/images/board-2.png" },
    { title: "EcoGlow Visual Identity", image: "https://via.placeholder.com/400x300?text=EcoGlow+Board" },
    { title: "NovaAI Startup Theme", image: "https://via.placeholder.com/400x300?text=NovaAI+Board" },
    { title: "Wavewear Fashion Pack", image: "https://via.placeholder.com/400x300?text=Wavewear+Board" },
  ];

  return (
    <div className="min-h-screen flex bg-[#222831] font-sans text-[#EEEEEE]">
      <div className="flex-1 w-full">
        <HeaderGreen />
        <main className="p-6 pt-28 md:pt-24 max-w-7xl mx-auto">
          <div className="mb-8">
            <h1 className="text-4xl font-bold text-[#FFD369] tracking-tight">AI Branding Boards</h1>
            <p className="mt-2 text-[#CCCCCC] text-sm">
              Browse professionally crafted branding kits and visual themes generated by AI.
            </p>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
            {brandingBoards.map((board, idx) => (
              <div
                key={idx}
                className="bg-[#393E46] rounded-xl overflow-hidden shadow group hover:shadow-xl hover:scale-[1.01] transition-all duration-300"
              >
                <img
                  src={board.image}
                  alt={board.title}
                  className="w-full h-56 object-cover"
                />
                <div className="p-4">
                  <h3 className="text-lg font-semibold text-[#FFD369]">{board.title}</h3>
                </div>
              </div>
            ))}
          </div>
        </main>
      </div>
    </div>
  );
}



